### PR TITLE
[EXAMPLE] added local-benthos-hasura example code

### PR DESCRIPTION
**Pull request by yourbuddyconner**
Was riffing with @jeffling about examples this afternoon and put this together to demonstrate my ideas around "quick setup" for indexed.xyz. 

Goal for this is to show an opinionated <10-minute clone-to-query installation which leverages the existing (super good) benthos example. 

Didn't put much time into fleshing out the README beyond removing the parts that became irrelevant and adding stuff about docker-compose. 

I desire some feedback, happy to iterate on this before merging.

### CODE REVIEW

**Comment by yourbuddyconner** [comment]
Some stuff I thought of since I made this PR: 
- Ran into the "disk is full because downloading massive parquet file" issue
- I think there should be an easy to use GoldSky CLI container that can be slotted into the Benthos pipeline that does the remapping benthos is doing + the in-memory streaming filtering operation from the CLI 
- This enables workflows where the GoldSky cli is a deployment dependency

**Comment by radiofreejohn** [comment]
I like this, I also like the general idea of adding some structure to the repo for examples.

One idea I have that could help limit the on-disk size would be to add a Benthos mapping that checks against the desired address and if it doesn't match it [deletes](https://www.benthos.dev/docs/guides/bloblang/functions#deleted) that message, or implementing some rejection [technique](https://www.benthos.dev/docs/components/outputs/reject).

**Comment by yourbuddyconner** [comment]
Cool I will take a looksie at that!

**Comment by yourbuddyconner** [comment]
That worked great, though with the schema being partitioned by year it _looks_ like nothing is happening given the O(n) search from beginning of the chain. 

Opted to pin it to `dt=2023` which I think is actually fine for this toy example.

**Comment by radiofreejohn** [comment]
Awesome, going to merge this then get to work moving the other examples into the directory structure

**Pull request merged**
